
###
//                                  GET  
###
GET http://localhost:3001/api/first
###
GET http://localhost:3001/api/second
###
GET http://localhost:3001/api/third
###
###
GET http://localhost:3001/api/fourth
###





###
//                                    POST
###
Post http://localhost:3001/api/first
Content-Type: application/json

{
  "quantity": "String for Some"
}
###
Post http://localhost:3001/api/second
Content-Type: application/json

{
    "quantity": 1
}
###
Post http://localhost:3001/api/third
Content-Type: application/json

{
    "OTOTMFourthId": 1,
    "OTOTMSecondId": 1
}
###
Post http://localhost:3001/api/fourth
Content-Type: application/json

{
    "OTOTMFirstId": 1
}





###
//                                  PUT
###
PUT http://localhost:3001/api/first/1
Content-Type: application/json
 
{
    "quantity": "My Guys"
}
###
PUT  http://localhost:3001/api/second/3
Content-Type: application/json
 
{
    "quantity": 2
}
###
###
PUT  http://localhost:3001/api/third
Content-Type: application/json
 
{
    "OTOTMFirstId": 5
}
###
###
PUT  http://localhost:3001/api/third
Content-Type: application/json
 
{
    "OTOTMSecondId": 5
}
###
###
PUT  http://localhost:3001/api/fourth
Content-Type: application/json
 
{
    "OTOTMSecondId": 5
}
###





###
//                                  DELETE
###
DELETE  http://localhost:3001/api/first/1
Content-Type: application/json
###
DELETE http://localhost:3001/api/second/1
Content-Type: application/json
###
DELETE http://localhost:3001/api/third
Content-Type: application/json

{
    "OTOTMFourthId": 2,
    "OTOTMSecondId": 6
}
###
DELETE http://localhost:3001/api/fourth
Content-Type: application/json

{
    "OTOTMFirstId": 2,
    "OTOTMSecondId": 6
}